name: ${NAME}

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  minio_data:

services:
  mysql:
    container_name: "${NAME}-mysql_db"
    image: mysql:8.0
    profiles:
      - back
      - front
      - local
      - db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
  minio:
    container_name: "${NAME}-minio"
    image: quay.io/minio/minio
    profiles:
      - back
      - front
      - local
      - db # Añadido perfil db
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PORT_WEB}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 20s
  backend:
    container_name: "${NAME}-backend_spring_boot"
    profiles:
      - back
      - local
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - app-network
  frontend:
    container_name: "${NAME}-frontend_react"
    profiles:
      - front
      - local
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "${PORT_FRONT}:80"
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - app-network
